name: flutter_grandparents_v00
description: "Un nuevo proyecto de Flutter."

# La siguiente línea evita que el paquete se publique accidentalmente en
# pub.dev usando `flutter pub publish`. Esto es preferible para paquetes privados.
publish_to: 'none' # Elimina esta línea si deseas publicar en pub.dev

# Lo siguiente define la versión y el número de compilación para tu aplicación.
# Un número de versión son tres números separados por puntos, como 1.2.43
# seguido de un número de compilación opcional separado por un +.
# Tanto la versión como el número de compilación pueden ser sobreescritos en flutter
# build especificando --build-name y --build-number, respectivamente.
# En Android, build-name se usa como versionName mientras que build-number se usa como versionCode.
# Lee más sobre el versionado de Android en https://developer.android.com/studio/publish/versioning
# En iOS, build-name se usa como CFBundleShortVersionString mientras que build-number se usa como CFBundleVersion.
# Lee más sobre el versionado de iOS en
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# En Windows, build-name se usa como las partes mayor, menor y de parche
# de las versiones del producto y del archivo, mientras que build-number se usa como el sufijo de compilación.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Las dependencias especifican otros paquetes que tu paquete necesita para funcionar.
# Para actualizar automáticamente las dependencias de tu paquete a las últimas versiones
# considera ejecutar `flutter pub upgrade --major-versions`. Alternativamente,
# las dependencias se pueden actualizar manualmente cambiando los números de versión a continuación a
# la última versión disponible en pub.dev. Para ver qué dependencias tienen nuevas
# versiones disponibles, ejecuta `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Lo siguiente agrega la fuente de iconos de Cupertino a tu aplicación.
  # Úsala con la clase CupertinoIcons para iconos de estilo iOS.
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  

  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # El paquete "flutter_lints" a continuación contiene un conjunto de lints recomendados para
  # fomentar buenas prácticas de codificación. El conjunto de lints proporcionado por el paquete se
  # activa en el archivo `analysis_options.yaml` ubicado en la raíz de tu
  # paquete. Consulta ese archivo para obtener información sobre cómo desactivar reglas de lint específicas
  # y activar otras adicionales.
  flutter_lints: ^5.0.0

# Para obtener información sobre la parte genérica de Dart de este archivo, consulta la
# siguiente página: https://dart.dev/tools/pub/pubspec

# La siguiente sección es específica para los paquetes de Flutter.
flutter:

  # La siguiente línea asegura que la fuente de iconos de Material
  # se incluya con tu aplicación, para que puedas usar los iconos en
  # la clase de iconos de Material.
  uses-material-design: true

  # Para agregar activos a tu aplicación, agrega una sección de activos, como esta:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Un activo de imagen puede hacer referencia a una o más "variantes" específicas de resolución, consulta
  # https://flutter.dev/to/resolution-aware-images

  # Para obtener detalles sobre cómo agregar activos desde dependencias de paquetes, consulta
  # https://flutter.dev/to/asset-from-package

  # Para agregar fuentes personalizadas a tu aplicación, agrega una sección de fuentes aquí,
  # en esta sección "flutter". Cada entrada en esta lista debe tener una
  # clave "family" con el nombre de la familia de fuentes, y una clave "fonts" con una
  # lista que proporciona el activo y otros descriptores para la fuente. Por
  # ejemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para obtener detalles sobre las fuentes de las dependencias de paquetes,
  # consulta https://flutter.dev/to/font-from-package